name: pomodoro_jjang_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ^3.32.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  collection: ^1.19.1
  intl: ^0.20.2
  go_router: ^15.2.4
  logger: ^2.6.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  http: ^1.4.0
  flutter_easyloading: ^3.0.5
  flutter_cache_manager: ^3.4.1

  # freezed, json_serializable, riverpod, hooks
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  # freezed, json_serializable, riverpod, hooks
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  # flutter_hooks_lint: ^1.3.1
  custom_lint: ^0.7.5
  go_router_builder: ^3.0.0
  flutter_gen_runner: ^5.10.0
  build_version: ^2.1.1
  icons_launcher: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: suit-variable
      fonts:
        - asset: fonts/SUIT-Variable.ttf
    - family: suit-static
      fonts:
        - asset: fonts/SUIT-Heavy.ttf
          weight: 900
        - asset: fonts/SUIT-ExtraBold.ttf
          weight: 800
        - asset: fonts/SUIT-Bold.ttf
          weight: 700
        - asset: fonts/SUIT-Semibold.ttf
          weight: 600
        - asset: fonts/SUIT-Medium.ttf
          weight: 500
        - asset: fonts/SUIT-Regular.ttf
          weight: 400
        - asset: fonts/SUIT-Light.ttf
          weight: 300
        - asset: fonts/SUIT-ExtraLight.ttf
          weight: 200
        - asset: fonts/SUIT-Thin.ttf
          weight: 100


